name: Build a Docker Image and push it to AWS ECR

on:
 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_ECR_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Automatic Tagging of Releases
      id: increment-git-tag
      run: |
        chmod +x version.sh
        ./version.sh -v minor

      #        OR
      # chmod +x ./version.sh
      # bash ./version .sh -v minor
    
    # - name: Generate tags
    #   id: docker_tags
    #   uses: dnaka91/action-docker-tags@v0.1
    #   with:
    #     registries: |
    #       docker.io
    #       ghcr.io
    #       quay.io            
           
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
        IMAGE_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        # IMAGE_TAG: ${{ steps.docker_tags.outputs.tags }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
          ##Prerequisite
# 1) Create a github Account
# - a) Create  a repository in Github.
# 2 Create an AWS Account
# - a) Create an AWS ECR repository in your AWS account.
# - b) Create an IAM user in your WAS account.  
# - C) Generate "AWS Access Key ID" and "AWS Secret Access Key for the User" and save in a save location. 

# 3) Create secrets in github repository. These secrets serve as evnironment variables in the workflows file. 
#    For environment variables, put the:
# - a) value of AWS_ACCESS_KEY_ID as the IAM user AWS Access Key ID.
# - b) value of AWS_SECRETE_ACCESS_KEY as IAM user AWS Secret Access Key. 
# - c) value of AWS_ECR_REGION as the Region of your AWS account. 

# 4) The version bash files, "version.sh and version2.sh" are version files used for image tag. 
# - Any of the versions provides a very short image-tag to the image built and pushed to the AWS ECR repository. 
# - These two version files CANNOT be at once. Only one of them should be used in the workflows file.
# - For "version.sh", the version number parts are 'major', 'minor', and 'patch'.
# - For "version2.sh", the version number parts are 'Release', 'Hotfix', and 'Patch'.

# NB: Remember to change the version number part anytime you update your workflows. If the last version number part was...
#...'major', then the new one should be 'minor' or 'patch', if your are using "version.sh". If you are using "version2.sh",...
#...you should be using 'Release', or 'Hotfix', or 'Patch' for version number part. All depends on you.

                                                    #GOOD LUCK !!!

