name: Built a Docker Image and push it to ECR

on:
 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRETE_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_ECR_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
        IMAGE_TAG: version-3
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

#Refeerence: https://youtu.be/6O-7zb-igUs?si=yBtGJu-eD3f8MRRf  
#Reference 1: https://youtu.be/yv8-Si5AB3U?si=8VVBFVtBXH5DqVE7
#Reference 2: https://youtu.be/m1OFz_Y9bYo?si=wSyEw9l7swBTdr8v
#Reference 3: https://youtu.be/PIzROR12fLs?si=nBWV6-M8D078fEXs
#Reference 4: https://youtu.be/rRes9LM-Jh8?si=qUmtzaOFxwXTqQ0A
#Reference 5: https://youtu.be/6O-7zb-igUs?si=XPf6KGk9n5t84PeI
#Referece 6:  https://youtu.be/m1OFz_Y9bYo?si=Zyd5OXpSXnkQgGke
#Reference 7: https://youtu.be/usZk3syhYPo?si=JLaMCSgFHBM6sCp6
#Reference 8: https://youtu.be/yv8-Si5AB3U?si=azLRkZTa_usEYv52
#Reference 9: https://youtu.be/UL7MKjTvJLk?si=fw9rhenWgpP0OAwp
#Reference 10: https://youtu.be/ZpPT1a8Gdac?si=BpEY8UOmG1IJFClA
#Reference 11: https://youtu.be/rRes9LM-Jh8?si=nW-rofWBNfvtNk4L 
